version: '3'

services:
  mysql:
    image: mysql:8.0.31
    container_name: alnitak-mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: AlnitakRoot@123
      MYSQL_DATABASE: alnitak
    restart: on-failure
    volumes:
      - ./data/mysql/db:/var/lib/mysql
      - ./data/mysql/init:/docker-entrypoint-initdb.d/
    ports:
      - '3307:3306'
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --character-set-client-handshake=false
      --init-connect='SET NAMES utf8mb4'

  #Redis
  redis:
    image: redis
    container_name: alnitak-redis
    command: redis-server --requirepass AlnitakRedis@123 # requirepass后为密码(可修改)
    ports:
      - "6380:6379"
    volumes:
      - ./data/redis:/data

  # 后端
  api:
    container_name: alnitak-api
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    working_dir: /server
    environment:
      TZ: Asia/Shanghai
    volumes:
      # 挂载文件
      - ./data/upload:/server/upload
      - ./data/logs/:/server/logs
      - ./data/config:/server/conf
    ports:
      # 映射端口
      - "9000:9000"
    depends_on:
      - mysql
      - redis
